[package]
name = "game_of_life"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4"
rand = "0.10"
rayon = "1.12"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"

[profile.wasm-release]
inherits = "release"
opt-level = "s"
strip = "debuginfo"
